- hosts: all
  become: true
  roles:
   - role: commons

- hosts: servidores_bd
  become: true
  roles:
   - mariadb
   - wordpress_bd

#- name: Configurar Apache2 y PHP-FPM
#  hosts: servidores_web
#  become: yes
#  roles:
#    - apache2_php-fpm

- hosts: servidores_web
  become: yes
  roles:
    - nginx_php-fpm
    - instalar_cms
